
BEGIN EXECUTE IMMEDIATE 'DROP TABLE detalle_venta CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE venta CASCADE CONSTRAINTS';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE vendedor CASCADE CONSTRAINTS';      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE empleado CASCADE CONSTRAINTS';      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE producto CASCADE CONSTRAINTS';      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE marca CASCADE CONSTRAINTS';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE proveedor CASCADE CONSTRAINTS';     EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE medio_pago CASCADE CONSTRAINTS';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE salud CASCADE CONSTRAINTS';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE afp CASCADE CONSTRAINTS';           EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_salud';                       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_empleado';                    EXCEPTION WHEN OTHERS THEN NULL; END;
/

/* =========================================================
   1) CREATE TABLES (CASO 1) – PK/FK/UN básicos
   ========================================================= */

-- AFP (IDENTITY: START 210 INCREMENT 6)
CREATE TABLE afp (
  id_afp  NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 210 INCREMENT BY 6) PRIMARY KEY,
  nombre  VARCHAR2(100) NOT NULL
);
ALTER TABLE afp ADD CONSTRAINT uq_afp_nombre UNIQUE (nombre);

-- SALUD (se poblará con SEQUENCE)
CREATE TABLE salud (
  id_salud NUMBER PRIMARY KEY,
  nombre   VARCHAR2(100) NOT NULL
);
ALTER TABLE salud ADD CONSTRAINT uq_salud_nombre UNIQUE (nombre);

-- MEDIO_PAGO (catálogo)
CREATE TABLE medio_pago (
  id_medio_pago NUMBER PRIMARY KEY,
  nombre        VARCHAR2(60) NOT NULL
);
ALTER TABLE medio_pago ADD CONSTRAINT uq_mediopago_nombre UNIQUE (nombre);

-- MARCA (catálogo)
CREATE TABLE marca (
  id_marca NUMBER PRIMARY KEY,
  nombre   VARCHAR2(100) NOT NULL
);

-- PROVEEDOR (catálogo)
CREATE TABLE proveedor (
  id_proveedor NUMBER PRIMARY KEY,
  nombre       VARCHAR2(120) NOT NULL,
  email        VARCHAR2(150)
);
ALTER TABLE proveedor ADD CONSTRAINT uq_proveedor_nombre UNIQUE (nombre);

-- PRODUCTO (FK -> MARCA; opcionalmente -> PROVEEDOR)
CREATE TABLE producto (
  id_producto NUMBER PRIMARY KEY,
  nombre      VARCHAR2(150) NOT NULL,
  id_marca    NUMBER NOT NULL,
  stock       NUMBER(10) DEFAULT 0,
  stock_min   NUMBER(10) DEFAULT 0
);
ALTER TABLE producto
  ADD CONSTRAINT fk_producto_marca FOREIGN KEY (id_marca)
  REFERENCES marca(id_marca);

-- EMPLEADO (se poblará con SEQUENCE; FK -> AFP, SALUD)
CREATE TABLE empleado (
  id_empleado   NUMBER PRIMARY KEY,
  nombre        VARCHAR2(120) NOT NULL,
  ape_paterno   VARCHAR2(60)  NOT NULL,
  ape_materno   VARCHAR2(60),
  activo        CHAR(1)       DEFAULT 'S' CHECK (activo IN ('S','N')),
  sueldo_base   NUMBER(10)    NOT NULL,
  bono_jefatura NUMBER(10),
  id_afp        NUMBER,
  id_salud      NUMBER,
  CONSTRAINT fk_empleado_afp   FOREIGN KEY (id_afp)   REFERENCES afp(id_afp),
  CONSTRAINT fk_empleado_salud FOREIGN KEY (id_salud) REFERENCES salud(id_salud)
);

-- VENDEDOR (subconjunto de EMPLEADO: PK=FK)
CREATE TABLE vendedor (
  id_empleado NUMBER PRIMARY KEY,
  comision    NUMBER(5,4),
  CONSTRAINT fk_vendedor_empleado FOREIGN KEY (id_empleado)
    REFERENCES empleado(id_empleado)
);

-- VENTA (IDENTITY: START 5050 INCREMENT 3; FK -> MEDIO_PAGO; opcional FK -> VENDEDOR)
CREATE TABLE venta (
  id_venta     NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 5050 INCREMENT BY 3) PRIMARY KEY,
  fecha        DATE NOT NULL,
  id_medio_pago NUMBER NOT NULL,
  id_empleado   NUMBER,
  CONSTRAINT fk_venta_mediopago FOREIGN KEY (id_medio_pago)
    REFERENCES medio_pago(id_medio_pago),
  CONSTRAINT fk_venta_vendedor FOREIGN KEY (id_empleado)
    REFERENCES vendedor(id_empleado)
);

-- DETALLE_VENTA (cabecera/detalle; PK compuesta; FK -> VENTA, PRODUCTO)
CREATE TABLE detalle_venta (
  id_venta    NUMBER NOT NULL,
  id_producto NUMBER NOT NULL,
  cantidad    NUMBER(10) NOT NULL,
  precio_unit NUMBER(10) NOT NULL,
  CONSTRAINT pk_detalle_venta PRIMARY KEY (id_venta, id_producto),
  CONSTRAINT fk_detvta_venta    FOREIGN KEY (id_venta)    REFERENCES venta(id_venta),
  CONSTRAINT fk_detvta_producto FOREIGN KEY (id_producto) REFERENCES producto(id_producto)
);

/* =========================================================
   2) ALTER TABLE (CASO 2) – Reglas de negocio explícitas
   ========================================================= */

-- Sueldo mínimo
ALTER TABLE empleado
  ADD CONSTRAINT ck_empleado_sueldo_min CHECK (sueldo_base >= 400000);

-- Comisión entre 0 y 0.25
ALTER TABLE vendedor
  ADD CONSTRAINT ck_vendedor_comision CHECK (comision >= 0 AND comision <= 0.25);

-- Stock mínimo del producto (al menos 3)
ALTER TABLE producto
  ADD CONSTRAINT ck_producto_stockmin CHECK (stock_min >= 3);

-- Email proveedor único
ALTER TABLE proveedor
  ADD CONSTRAINT uq_proveedor_email UNIQUE (email);

-- Marca única
ALTER TABLE marca
  ADD CONSTRAINT uq_marca_nombre UNIQUE (nombre);

-- Cantidad positiva en detalle de venta (> 0)
ALTER TABLE detalle_venta
  ADD CONSTRAINT ck_detvta_cantidad CHECK (cantidad > 0);

/* =========================================================
   3) SEQUENCES (CASO 3)
   ========================================================= */

-- SALUD: START 2050 INCREMENT 10
CREATE SEQUENCE seq_salud    START WITH 2050 INCREMENT BY 10 NOCACHE;

-- EMPLEADO: START 750 INCREMENT 3
CREATE SEQUENCE seq_empleado START WITH 750  INCREMENT BY 3  NOCACHE;

/* =========================================================
   4) INSERTS mínimos (CASO 3) – respetando dependencias
   ========================================================= */

-- AFP (IDENTITY) – ejemplos
INSERT INTO afp (nombre) VALUES ('Habitat');         -- id_afp = 210
INSERT INTO afp (nombre) VALUES ('Provida');         -- id_afp = 216

-- SALUD (SEQUENCE)
INSERT INTO salud (id_salud, nombre) VALUES (seq_salud.NEXTVAL, 'Fonasa');   -- 2050
INSERT INTO salud (id_salud, nombre) VALUES (seq_salud.NEXTVAL, 'Colmena');  -- 2060

-- MEDIO_PAGO
INSERT INTO medio_pago (id_medio_pago, nombre) VALUES (1, 'Efectivo');
INSERT INTO medio_pago (id_medio_pago, nombre) VALUES (2, 'Tarjeta');

-- MARCA
INSERT INTO marca (id_marca, nombre) VALUES (10, 'ACME');
INSERT INTO marca (id_marca, nombre) VALUES (20, 'OmniCorp');

-- PROVEEDOR
INSERT INTO proveedor (id_proveedor, nombre, email) VALUES (100, 'Suministros Chile', 'contacto@suministros.cl');
INSERT INTO proveedor (id_proveedor, nombre, email) VALUES (200, 'Distribuciones Max', 'ventas@max.cl');

-- PRODUCTO
INSERT INTO producto (id_producto, nombre, id_marca, stock, stock_min)
VALUES (1000, 'Teclado Mecánico', 10, 50, 5);
INSERT INTO producto (id_producto, nombre, id_marca, stock, stock_min)
VALUES (2000, 'Mouse Inalámbrico', 20, 80, 3);

-- EMPLEADO (SEQUENCE)
INSERT INTO empleado (id_empleado, nombre, ape_paterno, ape_materno, activo, sueldo_base, bono_jefatura, id_afp, id_salud)
VALUES (seq_empleado.NEXTVAL, 'Ana', 'Pérez', 'Gómez', 'S', 650000,  50000, 210, 2050);  -- 750
INSERT INTO empleado (id_empleado, nombre, ape_paterno, ape_materno, activo, sueldo_base, bono_jefatura, id_afp, id_salud)
VALUES (seq_empleado.NEXTVAL, 'Juan', 'Rojas', NULL,    'S', 520000,  NULL,   216, 2060);  -- 753

-- VENDEDOR (subtipo de EMPLEADO)
INSERT INTO vendedor (id_empleado, comision) VALUES (750, 0.10);
INSERT INTO vendedor (id_empleado, comision) VALUES (753, 0.15);

-- VENTA (IDENTITY)
INSERT INTO venta (fecha, id_medio_pago, id_empleado) VALUES (DATE '2025-09-01', 1, 750); -- id_venta = 5050
INSERT INTO venta (fecha, id_medio_pago, id_empleado) VALUES (DATE '2025-09-02', 2, 753); -- id_venta = 5053

-- DETALLE_VENTA
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unit)
VALUES (5050, 1000, 2, 39990);
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unit)
VALUES (5053, 2000, 1, 19990);

/* =========================================================
   5) SELECT * de verificación rápida
   ========================================================= */
SELECT * FROM afp;
SELECT * FROM salud;
SELECT * FROM medio_pago;
SELECT * FROM marca;
SELECT * FROM proveedor;
SELECT * FROM producto;
SELECT * FROM empleado;
SELECT * FROM vendedor;
SELECT * FROM venta;
SELECT * FROM detalle_venta;

/* =========================================================
   6) INFORMES (CASO 4)
   ========================================================= */

-- INFORME 1:
-- Activos con bono, salario simulado = sueldo + bono
-- Orden: SALARIO SIMULADO DESC, empate por ape_paterno DESC
SELECT
  e.id_empleado                                                AS "IDENTIFICADOR",
  e.nombre || ' ' || e.ape_paterno || ' ' || NVL(e.ape_materno,'') AS "NOMBRE COMPLETO",
  e.sueldo_base                                                AS "SALARIO",
  e.bono_jefatura                                             AS "BONIFICACION",
  (e.sueldo_base + e.bono_jefatura)                           AS "SALARIO SIMULADO"
FROM empleado e
WHERE e.activo = 'S'
  AND e.bono_jefatura IS NOT NULL
ORDER BY "SALARIO SIMULADO" DESC, e.ape_paterno DESC;

-- INFORME 2:
-- Sueldo entre 550k y 800k; +8% simulado
-- Orden: sueldo actual ASC
SELECT
  e.nombre || ' ' || e.ape_paterno || ' ' || NVL(e.ape_materno,'') AS "EMPLEADO",
  e.sueldo_base                                                    AS "SUELDO",
  0.08                                                             AS "POSIBLE AUMENTO",
  (e.sueldo_base * 1.08)                                           AS "SALARIO SIMULADO"
FROM empleado e
WHERE e.sueldo_base BETWEEN 550000 AND 800000
ORDER BY e.sueldo_base ASC;